version: 2

sources:
  - name: bronze
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: bronze_dev
    description: "Raw data tables for the operational system"
    tables:
      - name: customer
        description: Customer master data

      - name: orders
        description: Order header data

      - name: lineitem
        description: Order line item details

      - name: part
        description: Part master data

      - name: supplier
        description: Supplier master data

      - name: nation
        description: Nation reference data

      - name: region
        description: Region reference data

      - name: partsupp
        description: Part Supplier relationship data with supply cost
